name: Spustit ETL každou hodinu

on:
  schedule:
    - cron: '0 * * * *'  # každou hodinu
  workflow_dispatch:     # možnost ručně spustit přes GitHub UI

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kódu
        uses: actions/checkout@v3

      - name: Nastavit Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalace závislostí
        run: |
          pip install -r requirements.txt

      - name: Spustit skript
        run: python main.py
